import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import NextIntlProvider from "@/context/next-intl-client";
import Spinner from "../components/layout/Spinner";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | The Coffee Class",
    default: "The Coffee Class",
  },
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  },
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  let messages;

  try {
    messages = (await import(`../../translations/${locale}.json`)).default;
  } catch (error) {
    <Spinner />;
  }

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlProvider locale={locale} messages={messages}>
          {children}
        </NextIntlProvider>
        <Analytics />
      </body>
    </html>
  );
}
